// Relic-Tags — identical to Perk-Tags for synergy matching
export const RELIC_TAGS = {
  STREAK: 'streak',
  SPEED: 'speed',
  SCORE: 'score',
  DEFENSE: 'defense',
  XP: 'xp',
  LUCK: 'luck',
  FAKE: 'fake',
  SACRIFICE: 'sacrifice',
};

export const RELIC_RARITY = {
  COMMON: 'common',
  RARE: 'rare',
  EPIC: 'epic',
  LEGENDARY: 'legendary',
};

export const RELICS = {
  COMBO_MASTER: {
    id: 'combo_master',
    name: 'Combo Master',
    description: 'Every 3-streak adds +5% to your global score multiplier (stacks!)',
    icon: '🔗',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.STREAK, RELIC_TAGS.SCORE],
    effect: 'streak_multiplier_stack',
    value: 0.05,
    triggerEvery: 3,
  },
  MOMENTUM: {
    id: 'momentum',
    name: 'Momentum',
    description: 'Each consecutive correct answer gives +2 more XP than the previous',
    icon: '🚀',
    rarity: RELIC_RARITY.COMMON,
    tags: [RELIC_TAGS.STREAK, RELIC_TAGS.XP],
    effect: 'streak_xp_scaling',
    value: 2,
  },
  PRICE_SENSE: {
    id: 'price_sense',
    name: 'Price Sense',
    description: 'Cards with >$10 price difference grant 1.5x XP',
    icon: '💰',
    rarity: RELIC_RARITY.COMMON,
    tags: [RELIC_TAGS.XP, RELIC_TAGS.SCORE],
    effect: 'price_diff_xp_bonus',
    value: 1.5,
    threshold: 10,
  },
  LUCKY_CHARM: {
    id: 'lucky_charm',
    name: 'Lucky Charm',
    description: 'Rare perks appear 20% more often',
    icon: '🍀',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.LUCK],
    effect: 'rare_perk_boost',
    value: 0.2,
  },
  GLASS_CANNON: {
    id: 'glass_cannon',
    name: 'Glass Cannon',
    description: '2x score, but maximum 1 life',
    icon: '💥',
    rarity: RELIC_RARITY.EPIC,
    tags: [RELIC_TAGS.SCORE],
    effect: 'glass_cannon',
    value: 2,
  },
  QUICK_LEARNER: {
    id: 'quick_learner',
    name: 'Quick Learner',
    description: '+50% XP for answers within 3 seconds',
    icon: '⚡',
    rarity: RELIC_RARITY.COMMON,
    tags: [RELIC_TAGS.SPEED, RELIC_TAGS.XP],
    effect: 'speed_xp_bonus',
    value: 1.5,
    threshold: 3,
  },
  IRON_WILL: {
    id: 'iron_will',
    name: 'Iron Will',
    description: 'After a mistake: your next correct answer scores 3x',
    icon: '🛡️',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.DEFENSE, RELIC_TAGS.SCORE],
    effect: 'comeback_bonus',
    value: 3,
  },
  CARD_COUNTER: {
    id: 'card_counter',
    name: 'Card Counter',
    description: 'Every 10 rounds: +1 life (max 5)',
    icon: '🃏',
    rarity: RELIC_RARITY.EPIC,
    tags: [RELIC_TAGS.DEFENSE],
    effect: 'round_heal',
    value: 10,
  },
  TREASURE_HUNTER: {
    id: 'treasure_hunter',
    name: 'Treasure Hunter',
    description: '+25% more score from all perk bonuses',
    icon: '🗝️',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.SCORE, RELIC_TAGS.LUCK],
    effect: 'perk_bonus_amplifier',
    value: 1.25,
  },
  MEDITATION: {
    id: 'meditation',
    name: 'Meditation',
    description: 'Timer starts with +2 extra seconds',
    icon: '🧘',
    rarity: RELIC_RARITY.COMMON,
    tags: [RELIC_TAGS.SPEED, RELIC_TAGS.DEFENSE],
    effect: 'permanent_time_bonus',
    value: 2,
  },

  // === META-RELICS: Retrigger & Amplifier ===
  ECHO: {
    id: 'echo',
    name: 'Echo',
    description: 'All relic bonuses are applied twice',
    icon: '🔁',
    rarity: RELIC_RARITY.LEGENDARY,
    tags: [RELIC_TAGS.LUCK],
    effect: 'relic_retrigger',
    value: 2,
  },
  AMPLIFIER: {
    id: 'amplifier',
    name: 'Amplifier',
    description: 'All relic multipliers are 50% stronger',
    icon: '📡',
    rarity: RELIC_RARITY.EPIC,
    tags: [RELIC_TAGS.SCORE],
    effect: 'mult_amplifier',
    value: 1.5,
  },
  COLLECTOR_BONUS: {
    id: 'collector_bonus',
    name: 'Collector Bonus',
    description: '+15 flat score for each active relic',
    icon: '🏛️',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.SCORE],
    effect: 'per_relic_flat_bonus',
    value: 15,
  },
  SYNERGY_AMP: {
    id: 'synergy_amp',
    name: 'Synergy Amplifier',
    description: '+10% score per active synergy',
    icon: '🔗📡',
    rarity: RELIC_RARITY.LEGENDARY,
    tags: [RELIC_TAGS.SCORE, RELIC_TAGS.LUCK],
    effect: 'synergy_multiplier',
    value: 0.1,
  },

  // === META-RELICS: Converters ===
  ALCHEMIST: {
    id: 'alchemist',
    name: 'Alchemist',
    description: 'Flat bonuses convert to multipliers (+20 → ×1.2)',
    icon: '⚗️',
    rarity: RELIC_RARITY.EPIC,
    tags: [RELIC_TAGS.SCORE],
    effect: 'flat_to_mult',
    value: 0.01,
  },
  RISK_REWARD: {
    id: 'risk_reward',
    name: 'Risk & Reward',
    description: 'Less time remaining = higher multiplier (up to ×3)',
    icon: '🎲',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.SPEED, RELIC_TAGS.SCORE],
    effect: 'time_risk_mult',
    value: 3,
  },
  SNOWBALL: {
    id: 'snowball',
    name: 'Snowball',
    description: '+0.1× score per round played (stacks permanently)',
    icon: '☃️',
    rarity: RELIC_RARITY.EPIC,
    tags: [RELIC_TAGS.SCORE, RELIC_TAGS.STREAK],
    effect: 'round_scaling_mult',
    value: 0.1,
  },
  OVERKILL: {
    id: 'overkill',
    name: 'Overkill',
    description: 'Score above 100 per round: excess points are doubled',
    icon: '💀',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.SCORE],
    effect: 'overkill_bonus',
    value: 100,
  },

  // === META-RELICS: Meta-Scaling ===
  TAG_MASTER: {
    id: 'tag_master',
    name: 'Tag Master',
    description: '+0.1× score for each unique tag you own',
    icon: '🏷️',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.SCORE, RELIC_TAGS.LUCK],
    effect: 'unique_tag_mult',
    value: 0.1,
  },
  SYNERGY_CHAIN: {
    id: 'synergy_chain',
    name: 'Synergy Chain',
    description: 'Each active synergy adds +0.25× to all score multipliers',
    icon: '⛓️',
    rarity: RELIC_RARITY.EPIC,
    tags: [RELIC_TAGS.SCORE, RELIC_TAGS.LUCK],
    effect: 'per_synergy_mult',
    value: 0.25,
  },
  PERK_MASTERY: {
    id: 'perk_mastery',
    name: 'Perk Mastery',
    description: '+0.15× score per active perk',
    icon: '🎓',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.SCORE],
    effect: 'per_perk_mult',
    value: 0.15,
  },
  LEVEL_POWER: {
    id: 'level_power',
    name: 'Level Power',
    description: '+2% score per level (Level 10 = +20%)',
    icon: '📈',
    rarity: RELIC_RARITY.COMMON,
    tags: [RELIC_TAGS.SCORE, RELIC_TAGS.XP],
    effect: 'level_scaling',
    value: 0.02,
  },

  // === META-RELICS: Conditional Combos ===
  CHAIN_REACTION: {
    id: 'chain_reaction',
    name: 'Chain Reaction',
    description: 'When Iron Will or Combo Master is active: +50% bonus',
    icon: '💥⚡',
    rarity: RELIC_RARITY.LEGENDARY,
    tags: [RELIC_TAGS.SCORE, RELIC_TAGS.LUCK],
    effect: 'chain_reaction',
    value: 1.5,
  },
  PERFECTIONIST_ECHO: {
    id: 'perfectionist_echo',
    name: 'Perfectionist Echo',
    description: 'On a perfect answer (first second): next round all bonuses ×2',
    icon: '✨🔁',
    rarity: RELIC_RARITY.EPIC,
    tags: [RELIC_TAGS.SPEED, RELIC_TAGS.SCORE],
    effect: 'perfect_next_double',
    value: 2,
  },
  STREAK_SHIELD: {
    id: 'streak_shield',
    name: 'Streak Shield',
    description: 'On a mistake, streak is halved instead of reset to 0',
    icon: '🔥🛡️',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.STREAK, RELIC_TAGS.DEFENSE],
    effect: 'streak_preservation',
    value: 0.5,
  },
  LAST_STAND: {
    id: 'last_stand',
    name: 'Last Stand',
    description: 'On last life: all multipliers are applied again (×2)',
    icon: '⚔️',
    rarity: RELIC_RARITY.LEGENDARY,
    tags: [RELIC_TAGS.DEFENSE, RELIC_TAGS.SCORE],
    effect: 'last_stand_double',
    value: 2,
  },
  XP_CONVERTER: {
    id: 'xp_converter',
    name: 'XP Converter',
    description: 'Excess XP after leveling up converts to score (1 XP = 2 score)',
    icon: '💱',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.XP, RELIC_TAGS.SCORE],
    effect: 'xp_to_score',
    value: 2,
  },

  // === META-RELICS: Perk Enhancers ===
  ETERNAL_FLAME: {
    id: 'eternal_flame',
    name: 'Eternal Flame',
    description: 'Perks with a duration last 3 rounds longer',
    icon: '🕯️',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.LUCK],
    effect: 'perk_duration_extend',
    value: 3,
  },
  DOUBLE_DIP: {
    id: 'double_dip',
    name: 'Double Dip',
    description: 'When picking perks every 5 rounds: choose 2 instead of 1',
    icon: '✌️',
    rarity: RELIC_RARITY.LEGENDARY,
    tags: [RELIC_TAGS.LUCK],
    effect: 'double_perk_pick',
    value: 2,
  },
  UPGRADE_MASTER: {
    id: 'upgrade_master',
    name: 'Upgrade Master',
    description: 'Upgrades grant +2 upgrade count (double tag contribution)',
    icon: '⬆️⬆️',
    rarity: RELIC_RARITY.EPIC,
    tags: [RELIC_TAGS.LUCK, RELIC_TAGS.SCORE],
    effect: 'double_upgrade',
    value: 2,
  },
  PERK_RECYCLER: {
    id: 'perk_recycler',
    name: 'Perk Recycler',
    description: 'When a perk expires: 30% chance it renews itself',
    icon: '♻️',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.LUCK, RELIC_TAGS.DEFENSE],
    effect: 'perk_recycle_chance',
    value: 0.3,
  },

  // === CHEAT THE SYSTEM: Category 1 — Fake State ===
  DEATHS_MASK: {
    id: 'deaths_mask',
    name: "Death's Mask",
    description: 'You always count as having 1 life',
    icon: '💀',
    rarity: RELIC_RARITY.EPIC,
    tags: [RELIC_TAGS.FAKE, RELIC_TAGS.SCORE],
    effect: 'fake_one_hp',
    value: 1,
  },
  PHANTOM_STREAK: {
    id: 'phantom_streak',
    name: 'Phantom Streak',
    description: 'You always count as having at least a 10-streak',
    icon: '👻',
    rarity: RELIC_RARITY.EPIC,
    tags: [RELIC_TAGS.FAKE, RELIC_TAGS.STREAK],
    effect: 'fake_min_streak',
    value: 10,
  },
  TIMELESS: {
    id: 'timeless',
    name: 'Timeless',
    description: 'You always count as having answered instantly — all speed bonuses always trigger',
    icon: '⏳',
    rarity: RELIC_RARITY.EPIC,
    tags: [RELIC_TAGS.FAKE, RELIC_TAGS.SPEED],
    effect: 'fake_instant_answer',
    value: 1,
  },

  // === CHEAT THE SYSTEM: Category 2 — Rule Inversions ===
  REVERSE_TIMER: {
    id: 'reverse_timer',
    name: 'Reverse Timer',
    description: 'Less remaining time gives MORE time bonus instead of less',
    icon: '⏪',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.SCORE, RELIC_TAGS.SPEED],
    effect: 'reverse_time_bonus',
    value: 1,
  },
  PAIN_IS_GAIN: {
    id: 'pain_is_gain',
    name: 'Pain is Gain',
    description: 'When you lose a life: +50 score and +30 XP',
    icon: '🩸',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.SACRIFICE, RELIC_TAGS.SCORE],
    effect: 'damage_reward',
    value: 50,
    xpValue: 30,
  },
  OVERFLOW: {
    id: 'overflow',
    name: 'Overflow',
    description: 'Excess healing above max converts to score (100 score per heal)',
    icon: '🫀',
    rarity: RELIC_RARITY.EPIC,
    tags: [RELIC_TAGS.DEFENSE, RELIC_TAGS.SCORE],
    effect: 'overflow_hp_to_score',
    value: 100,
  },

  // === CHEAT THE SYSTEM: Category 3 — Item Hacking ===
  BLUEPRINT: {
    id: 'blueprint',
    name: 'Blueprint',
    description: 'Copies the effect of a random other relic',
    icon: '📋',
    rarity: RELIC_RARITY.LEGENDARY,
    tags: [RELIC_TAGS.LUCK],
    effect: 'blueprint_copy',
    value: 1,
  },
  PARASITE: {
    id: 'parasite',
    name: 'Parasite',
    description: 'Makes your next temporary perk permanent',
    icon: '🦠',
    rarity: RELIC_RARITY.LEGENDARY,
    tags: [RELIC_TAGS.LUCK, RELIC_TAGS.SCORE],
    effect: 'next_perk_permanent',
    value: 1,
    consumable: true,
  },
  MIRROR: {
    id: 'mirror',
    name: 'Mirror',
    description: 'With at least 2 active multipliers: +30% to total score',
    icon: '🪞',
    rarity: RELIC_RARITY.EPIC,
    tags: [RELIC_TAGS.SCORE],
    effect: 'equalize_multipliers',
    value: 1.3,
  },
  COPYCAT: {
    id: 'copycat',
    name: 'Copycat',
    description: 'Each perk pick also gives a copy with half values and half duration',
    icon: '🐱',
    rarity: RELIC_RARITY.EPIC,
    tags: [RELIC_TAGS.LUCK],
    effect: 'perk_copy_half',
    value: 0.5,
  },

  // === CHEAT THE SYSTEM: Category 4 — Anti-Synergies ===
  HERMIT: {
    id: 'hermit',
    name: 'Hermit',
    description: 'DISABLES all synergies. In return: all relic bonuses are twice as strong',
    icon: '🏚️',
    rarity: RELIC_RARITY.EPIC,
    tags: [RELIC_TAGS.SACRIFICE, RELIC_TAGS.SCORE],
    effect: 'disable_synergies_double_relics',
    value: 2,
  },
  MINIMALIST: {
    id: 'minimalist',
    name: 'Minimalist',
    description: 'Max. 3 relics. In return: all three are three times as strong',
    icon: '🧹',
    rarity: RELIC_RARITY.EPIC,
    tags: [RELIC_TAGS.SACRIFICE, RELIC_TAGS.SCORE],
    effect: 'max_relics_triple',
    value: 3,
    maxRelics: 3,
  },
  NO_PERKS: {
    id: 'no_perks',
    name: 'No Perks',
    description: 'No more perk picks. In return: +1 extra relic option at each level-up',
    icon: '🚫',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.SACRIFICE],
    effect: 'disable_perks_extra_relic',
    value: 1,
  },
};

export const RELIC_RARITY_WEIGHTS = {
  [RELIC_RARITY.COMMON]: 50,
  [RELIC_RARITY.RARE]: 30,
  [RELIC_RARITY.EPIC]: 15,
  [RELIC_RARITY.LEGENDARY]: 5,
};
