// Relic-Tags — identisch mit den Perk-Tags für Synergy-Matching
export const RELIC_TAGS = {
  STREAK: 'streak',
  SPEED: 'speed',
  SCORE: 'score',
  DEFENSE: 'defense',
  XP: 'xp',
  LUCK: 'luck',
};

export const RELIC_RARITY = {
  COMMON: 'common',
  RARE: 'rare',
  EPIC: 'epic',
  LEGENDARY: 'legendary',
};

export const RELICS = {
  COMBO_MASTER: {
    id: 'combo_master',
    name: 'Combo Master',
    description: 'Jede 3er-Streak gibt +5% globalen Score-Multiplikator (stackt!)',
    icon: '🔗',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.STREAK, RELIC_TAGS.SCORE],
    effect: 'streak_multiplier_stack',
    value: 0.05,
    triggerEvery: 3,
  },
  MOMENTUM: {
    id: 'momentum',
    name: 'Momentum',
    description: 'Jede richtige Antwort in Folge gibt +2 XP mehr als die vorherige',
    icon: '🚀',
    rarity: RELIC_RARITY.COMMON,
    tags: [RELIC_TAGS.STREAK, RELIC_TAGS.XP],
    effect: 'streak_xp_scaling',
    value: 2,
  },
  PRICE_SENSE: {
    id: 'price_sense',
    name: 'Price Sense',
    description: 'Karten mit >$10 Preisdifferenz geben 1.5x XP',
    icon: '💰',
    rarity: RELIC_RARITY.COMMON,
    tags: [RELIC_TAGS.XP, RELIC_TAGS.SCORE],
    effect: 'price_diff_xp_bonus',
    value: 1.5,
    threshold: 10,
  },
  LUCKY_CHARM: {
    id: 'lucky_charm',
    name: 'Lucky Charm',
    description: 'Seltene Perks erscheinen 20% häufiger',
    icon: '🍀',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.LUCK],
    effect: 'rare_perk_boost',
    value: 0.2,
  },
  GLASS_CANNON: {
    id: 'glass_cannon',
    name: 'Glass Cannon',
    description: '2x Score, aber max. 1 Leben',
    icon: '💥',
    rarity: RELIC_RARITY.EPIC,
    tags: [RELIC_TAGS.SCORE],
    effect: 'glass_cannon',
    value: 2,
  },
  QUICK_LEARNER: {
    id: 'quick_learner',
    name: 'Quick Learner',
    description: '+50% XP für Antworten unter 3 Sekunden',
    icon: '⚡',
    rarity: RELIC_RARITY.COMMON,
    tags: [RELIC_TAGS.SPEED, RELIC_TAGS.XP],
    effect: 'speed_xp_bonus',
    value: 1.5,
    threshold: 3,
  },
  IRON_WILL: {
    id: 'iron_will',
    name: 'Iron Will',
    description: 'Nach einem Fehler: nächste richtige Antwort gibt 3x Score',
    icon: '🛡️',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.DEFENSE, RELIC_TAGS.SCORE],
    effect: 'comeback_bonus',
    value: 3,
  },
  CARD_COUNTER: {
    id: 'card_counter',
    name: 'Card Counter',
    description: 'Alle 10 Runden: +1 Leben (max 5)',
    icon: '🃏',
    rarity: RELIC_RARITY.EPIC,
    tags: [RELIC_TAGS.DEFENSE],
    effect: 'round_heal',
    value: 10,
  },
  TREASURE_HUNTER: {
    id: 'treasure_hunter',
    name: 'Treasure Hunter',
    description: '+25% mehr Score von allen Perk-Boni',
    icon: '🗝️',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.SCORE, RELIC_TAGS.LUCK],
    effect: 'perk_bonus_amplifier',
    value: 1.25,
  },
  MEDITATION: {
    id: 'meditation',
    name: 'Meditation',
    description: 'Timer startet mit +2 Sekunden extra',
    icon: '🧘',
    rarity: RELIC_RARITY.COMMON,
    tags: [RELIC_TAGS.SPEED, RELIC_TAGS.DEFENSE],
    effect: 'permanent_time_bonus',
    value: 2,
  },
};

export const RELIC_RARITY_WEIGHTS = {
  [RELIC_RARITY.COMMON]: 50,
  [RELIC_RARITY.RARE]: 30,
  [RELIC_RARITY.EPIC]: 15,
  [RELIC_RARITY.LEGENDARY]: 5,
};
