// Relic-Tags — identisch mit den Perk-Tags für Synergy-Matching
export const RELIC_TAGS = {
  STREAK: 'streak',
  SPEED: 'speed',
  SCORE: 'score',
  DEFENSE: 'defense',
  XP: 'xp',
  LUCK: 'luck',
  FAKE: 'fake',
  SACRIFICE: 'sacrifice',
};

export const RELIC_RARITY = {
  COMMON: 'common',
  RARE: 'rare',
  EPIC: 'epic',
  LEGENDARY: 'legendary',
};

export const RELICS = {
  COMBO_MASTER: {
    id: 'combo_master',
    name: 'Combo Master',
    description: 'Jede 3er-Streak gibt +5% globalen Score-Multiplikator (stackt!)',
    icon: '🔗',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.STREAK, RELIC_TAGS.SCORE],
    effect: 'streak_multiplier_stack',
    value: 0.05,
    triggerEvery: 3,
  },
  MOMENTUM: {
    id: 'momentum',
    name: 'Momentum',
    description: 'Jede richtige Antwort in Folge gibt +2 XP mehr als die vorherige',
    icon: '🚀',
    rarity: RELIC_RARITY.COMMON,
    tags: [RELIC_TAGS.STREAK, RELIC_TAGS.XP],
    effect: 'streak_xp_scaling',
    value: 2,
  },
  PRICE_SENSE: {
    id: 'price_sense',
    name: 'Price Sense',
    description: 'Karten mit >$10 Preisdifferenz geben 1.5x XP',
    icon: '💰',
    rarity: RELIC_RARITY.COMMON,
    tags: [RELIC_TAGS.XP, RELIC_TAGS.SCORE],
    effect: 'price_diff_xp_bonus',
    value: 1.5,
    threshold: 10,
  },
  LUCKY_CHARM: {
    id: 'lucky_charm',
    name: 'Lucky Charm',
    description: 'Seltene Perks erscheinen 20% häufiger',
    icon: '🍀',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.LUCK],
    effect: 'rare_perk_boost',
    value: 0.2,
  },
  GLASS_CANNON: {
    id: 'glass_cannon',
    name: 'Glass Cannon',
    description: '2x Score, aber max. 1 Leben',
    icon: '💥',
    rarity: RELIC_RARITY.EPIC,
    tags: [RELIC_TAGS.SCORE],
    effect: 'glass_cannon',
    value: 2,
  },
  QUICK_LEARNER: {
    id: 'quick_learner',
    name: 'Quick Learner',
    description: '+50% XP für Antworten unter 3 Sekunden',
    icon: '⚡',
    rarity: RELIC_RARITY.COMMON,
    tags: [RELIC_TAGS.SPEED, RELIC_TAGS.XP],
    effect: 'speed_xp_bonus',
    value: 1.5,
    threshold: 3,
  },
  IRON_WILL: {
    id: 'iron_will',
    name: 'Iron Will',
    description: 'Nach einem Fehler: nächste richtige Antwort gibt 3x Score',
    icon: '🛡️',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.DEFENSE, RELIC_TAGS.SCORE],
    effect: 'comeback_bonus',
    value: 3,
  },
  CARD_COUNTER: {
    id: 'card_counter',
    name: 'Card Counter',
    description: 'Alle 10 Runden: +1 Leben (max 5)',
    icon: '🃏',
    rarity: RELIC_RARITY.EPIC,
    tags: [RELIC_TAGS.DEFENSE],
    effect: 'round_heal',
    value: 10,
  },
  TREASURE_HUNTER: {
    id: 'treasure_hunter',
    name: 'Treasure Hunter',
    description: '+25% mehr Score von allen Perk-Boni',
    icon: '🗝️',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.SCORE, RELIC_TAGS.LUCK],
    effect: 'perk_bonus_amplifier',
    value: 1.25,
  },
  MEDITATION: {
    id: 'meditation',
    name: 'Meditation',
    description: 'Timer startet mit +2 Sekunden extra',
    icon: '🧘',
    rarity: RELIC_RARITY.COMMON,
    tags: [RELIC_TAGS.SPEED, RELIC_TAGS.DEFENSE],
    effect: 'permanent_time_bonus',
    value: 2,
  },

  // === META-RELICS: Retrigger & Amplifier ===
  ECHO: {
    id: 'echo',
    name: 'Echo',
    description: 'Relic-Boni werden doppelt angerechnet',
    icon: '🔁',
    rarity: RELIC_RARITY.LEGENDARY,
    tags: [RELIC_TAGS.LUCK],
    effect: 'relic_retrigger',
    value: 2,
  },
  AMPLIFIER: {
    id: 'amplifier',
    name: 'Amplifier',
    description: 'Alle Relic-Multiplikatoren sind 50% stärker',
    icon: '📡',
    rarity: RELIC_RARITY.EPIC,
    tags: [RELIC_TAGS.SCORE],
    effect: 'mult_amplifier',
    value: 1.5,
  },
  COLLECTOR_BONUS: {
    id: 'collector_bonus',
    name: 'Collector Bonus',
    description: '+15 flat Score pro aktivem Relic',
    icon: '🏛️',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.SCORE],
    effect: 'per_relic_flat_bonus',
    value: 15,
  },
  SYNERGY_AMP: {
    id: 'synergy_amp',
    name: 'Synergy Amplifier',
    description: '+10% Score pro aktiver Synergy',
    icon: '🔗📡',
    rarity: RELIC_RARITY.LEGENDARY,
    tags: [RELIC_TAGS.SCORE, RELIC_TAGS.LUCK],
    effect: 'synergy_multiplier',
    value: 0.1,
  },

  // === META-RELICS: Konverter ===
  ALCHEMIST: {
    id: 'alchemist',
    name: 'Alchemist',
    description: 'Flat-Boni werden zu Multiplikatoren (+20 → ×1.2)',
    icon: '⚗️',
    rarity: RELIC_RARITY.EPIC,
    tags: [RELIC_TAGS.SCORE],
    effect: 'flat_to_mult',
    value: 0.01,
  },
  RISK_REWARD: {
    id: 'risk_reward',
    name: 'Risk & Reward',
    description: 'Weniger Restzeit = höherer Multiplikator (bis ×3)',
    icon: '🎲',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.SPEED, RELIC_TAGS.SCORE],
    effect: 'time_risk_mult',
    value: 3,
  },
  SNOWBALL: {
    id: 'snowball',
    name: 'Snowball',
    description: '+0.1× Score pro gespielte Runde (stackt permanent)',
    icon: '☃️',
    rarity: RELIC_RARITY.EPIC,
    tags: [RELIC_TAGS.SCORE, RELIC_TAGS.STREAK],
    effect: 'round_scaling_mult',
    value: 0.1,
  },
  OVERKILL: {
    id: 'overkill',
    name: 'Overkill',
    description: 'Score über 100 pro Runde: überschüssige Punkte werden verdoppelt',
    icon: '💀',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.SCORE],
    effect: 'overkill_bonus',
    value: 100,
  },

  // === META-RELICS: Meta-Scaling ===
  TAG_MASTER: {
    id: 'tag_master',
    name: 'Tag Master',
    description: '+0.1× Score pro einzigartigen Tag den du besitzt',
    icon: '🏷️',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.SCORE, RELIC_TAGS.LUCK],
    effect: 'unique_tag_mult',
    value: 0.1,
  },
  SYNERGY_CHAIN: {
    id: 'synergy_chain',
    name: 'Synergy Chain',
    description: 'Jede aktive Synergy gibt +0.25× auf alle Score-Multiplikatoren',
    icon: '⛓️',
    rarity: RELIC_RARITY.EPIC,
    tags: [RELIC_TAGS.SCORE, RELIC_TAGS.LUCK],
    effect: 'per_synergy_mult',
    value: 0.25,
  },
  PERK_MASTERY: {
    id: 'perk_mastery',
    name: 'Perk Mastery',
    description: '+0.15× Score pro aktivem Perk',
    icon: '🎓',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.SCORE],
    effect: 'per_perk_mult',
    value: 0.15,
  },
  LEVEL_POWER: {
    id: 'level_power',
    name: 'Level Power',
    description: '+2% Score pro Level (Level 10 = +20%)',
    icon: '📈',
    rarity: RELIC_RARITY.COMMON,
    tags: [RELIC_TAGS.SCORE, RELIC_TAGS.XP],
    effect: 'level_scaling',
    value: 0.02,
  },

  // === META-RELICS: Bedingungs-Combos ===
  CHAIN_REACTION: {
    id: 'chain_reaction',
    name: 'Chain Reaction',
    description: 'Wenn Iron Will oder Combo Master aktiv ist: +50% Bonus',
    icon: '💥⚡',
    rarity: RELIC_RARITY.LEGENDARY,
    tags: [RELIC_TAGS.SCORE, RELIC_TAGS.LUCK],
    effect: 'chain_reaction',
    value: 1.5,
  },
  PERFECTIONIST_ECHO: {
    id: 'perfectionist_echo',
    name: 'Perfectionist Echo',
    description: 'Bei perfekter Antwort (erste Sekunde): nächste Runde alle Boni ×2',
    icon: '✨🔁',
    rarity: RELIC_RARITY.EPIC,
    tags: [RELIC_TAGS.SPEED, RELIC_TAGS.SCORE],
    effect: 'perfect_next_double',
    value: 2,
  },
  STREAK_SHIELD: {
    id: 'streak_shield',
    name: 'Streak Shield',
    description: 'Bei Fehler wird Streak halbiert statt auf 0 gesetzt',
    icon: '🔥🛡️',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.STREAK, RELIC_TAGS.DEFENSE],
    effect: 'streak_preservation',
    value: 0.5,
  },
  LAST_STAND: {
    id: 'last_stand',
    name: 'Last Stand',
    description: 'Bei letztem Leben: alle Multiplikatoren nochmal angewendet (×2)',
    icon: '⚔️',
    rarity: RELIC_RARITY.LEGENDARY,
    tags: [RELIC_TAGS.DEFENSE, RELIC_TAGS.SCORE],
    effect: 'last_stand_double',
    value: 2,
  },
  XP_CONVERTER: {
    id: 'xp_converter',
    name: 'XP Converter',
    description: 'Überschüssige XP nach Level-Up → Score (1 XP = 2 Score)',
    icon: '💱',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.XP, RELIC_TAGS.SCORE],
    effect: 'xp_to_score',
    value: 2,
  },

  // === META-RELICS: Perk-Verstärker ===
  ETERNAL_FLAME: {
    id: 'eternal_flame',
    name: 'Eternal Flame',
    description: 'Perks mit Duration halten 3 Runden länger',
    icon: '🕯️',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.LUCK],
    effect: 'perk_duration_extend',
    value: 3,
  },
  DOUBLE_DIP: {
    id: 'double_dip',
    name: 'Double Dip',
    description: 'Beim Perk-Pick alle 5 Runden: wähle 2 statt 1',
    icon: '✌️',
    rarity: RELIC_RARITY.LEGENDARY,
    tags: [RELIC_TAGS.LUCK],
    effect: 'double_perk_pick',
    value: 2,
  },
  UPGRADE_MASTER: {
    id: 'upgrade_master',
    name: 'Upgrade Master',
    description: 'Upgrades geben +2 upgradeCount (doppelte Tag-Contribution)',
    icon: '⬆️⬆️',
    rarity: RELIC_RARITY.EPIC,
    tags: [RELIC_TAGS.LUCK, RELIC_TAGS.SCORE],
    effect: 'double_upgrade',
    value: 2,
  },
  PERK_RECYCLER: {
    id: 'perk_recycler',
    name: 'Perk Recycler',
    description: 'Wenn ein Perk ausläuft: 30% Chance dass er sich erneuert',
    icon: '♻️',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.LUCK, RELIC_TAGS.DEFENSE],
    effect: 'perk_recycle_chance',
    value: 0.3,
  },

  // === CHEAT THE SYSTEM: Kategorie 1 — Zustand faken ===
  DEATHS_MASK: {
    id: 'deaths_mask',
    name: "Death's Mask",
    description: 'Du zählst immer als hättest du 1 Leben',
    icon: '💀',
    rarity: RELIC_RARITY.EPIC,
    tags: [RELIC_TAGS.FAKE, RELIC_TAGS.SCORE],
    effect: 'fake_one_hp',
    value: 1,
  },
  PHANTOM_STREAK: {
    id: 'phantom_streak',
    name: 'Phantom Streak',
    description: 'Du zählst immer als hättest du mindestens 10er Streak',
    icon: '👻',
    rarity: RELIC_RARITY.EPIC,
    tags: [RELIC_TAGS.FAKE, RELIC_TAGS.STREAK],
    effect: 'fake_min_streak',
    value: 10,
  },
  TIMELESS: {
    id: 'timeless',
    name: 'Timeless',
    description: 'Du zählst immer als hättest du sofort geantwortet — alle Speed-Boni triggern immer',
    icon: '⏳',
    rarity: RELIC_RARITY.EPIC,
    tags: [RELIC_TAGS.FAKE, RELIC_TAGS.SPEED],
    effect: 'fake_instant_answer',
    value: 1,
  },

  // === CHEAT THE SYSTEM: Kategorie 2 — Regeln umdrehen ===
  REVERSE_TIMER: {
    id: 'reverse_timer',
    name: 'Reverse Timer',
    description: 'Weniger Restzeit gibt MEHR Time-Bonus statt weniger',
    icon: '⏪',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.SCORE, RELIC_TAGS.SPEED],
    effect: 'reverse_time_bonus',
    value: 1,
  },
  PAIN_IS_GAIN: {
    id: 'pain_is_gain',
    name: 'Pain is Gain',
    description: 'Wenn du ein Leben verlierst: +50 Score und +30 XP',
    icon: '🩸',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.SACRIFICE, RELIC_TAGS.SCORE],
    effect: 'damage_reward',
    value: 50,
    xpValue: 30,
  },
  OVERFLOW: {
    id: 'overflow',
    name: 'Overflow',
    description: 'Überschüssige Heilung über dem Max wird zu Score (100 Score pro Heal)',
    icon: '🫀',
    rarity: RELIC_RARITY.EPIC,
    tags: [RELIC_TAGS.DEFENSE, RELIC_TAGS.SCORE],
    effect: 'overflow_hp_to_score',
    value: 100,
  },

  // === CHEAT THE SYSTEM: Kategorie 3 — Items hacken ===
  BLUEPRINT: {
    id: 'blueprint',
    name: 'Blueprint',
    description: 'Kopiert den Effekt eines zufälligen anderen Relics',
    icon: '📋',
    rarity: RELIC_RARITY.LEGENDARY,
    tags: [RELIC_TAGS.LUCK],
    effect: 'blueprint_copy',
    value: 1,
  },
  PARASITE: {
    id: 'parasite',
    name: 'Parasite',
    description: 'Macht deinen nächsten temporären Perk permanent',
    icon: '🦠',
    rarity: RELIC_RARITY.LEGENDARY,
    tags: [RELIC_TAGS.LUCK, RELIC_TAGS.SCORE],
    effect: 'next_perk_permanent',
    value: 1,
    consumable: true,
  },
  MIRROR: {
    id: 'mirror',
    name: 'Mirror',
    description: 'Bei mind. 2 aktiven Multiplikatoren: +30% auf den Gesamt-Score',
    icon: '🪞',
    rarity: RELIC_RARITY.EPIC,
    tags: [RELIC_TAGS.SCORE],
    effect: 'equalize_multipliers',
    value: 1.3,
  },
  COPYCAT: {
    id: 'copycat',
    name: 'Copycat',
    description: 'Jeder Perk-Pick gibt zusätzlich eine Kopie mit halben Werten und halber Duration',
    icon: '🐱',
    rarity: RELIC_RARITY.EPIC,
    tags: [RELIC_TAGS.LUCK],
    effect: 'perk_copy_half',
    value: 0.5,
  },

  // === CHEAT THE SYSTEM: Kategorie 4 — Anti-Synergien ===
  HERMIT: {
    id: 'hermit',
    name: 'Hermit',
    description: 'DEAKTIVIERT alle Synergien. Dafür: alle Relic-Boni doppelt so stark',
    icon: '🏚️',
    rarity: RELIC_RARITY.EPIC,
    tags: [RELIC_TAGS.SACRIFICE, RELIC_TAGS.SCORE],
    effect: 'disable_synergies_double_relics',
    value: 2,
  },
  MINIMALIST: {
    id: 'minimalist',
    name: 'Minimalist',
    description: 'Max. 3 Relics. Dafür: alle drei sind dreifach so stark',
    icon: '🧹',
    rarity: RELIC_RARITY.EPIC,
    tags: [RELIC_TAGS.SACRIFICE, RELIC_TAGS.SCORE],
    effect: 'max_relics_triple',
    value: 3,
    maxRelics: 3,
  },
  NO_PERKS: {
    id: 'no_perks',
    name: 'No Perks',
    description: 'Keine Perk-Picks mehr. Dafür: +1 extra Relic-Option bei jedem Level-Up',
    icon: '🚫',
    rarity: RELIC_RARITY.RARE,
    tags: [RELIC_TAGS.SACRIFICE],
    effect: 'disable_perks_extra_relic',
    value: 1,
  },
};

export const RELIC_RARITY_WEIGHTS = {
  [RELIC_RARITY.COMMON]: 50,
  [RELIC_RARITY.RARE]: 30,
  [RELIC_RARITY.EPIC]: 15,
  [RELIC_RARITY.LEGENDARY]: 5,
};
