export const SYNERGIES = {
  SPEED_DEMON: {
    id: 'speed_demon_combo',
    name: 'Speed Demon',
    description: 'Alle Timer-Boni werden verdoppelt',
    icon: '⚡⚡',
    requiredTags: { speed: 2 },
    effect: 'double_time_bonus',
    value: 2,
  },
  FORTRESS: {
    id: 'fortress',
    name: 'Fortress',
    description: 'Herz-Regen alle 8 statt 15 richtige Antworten',
    icon: '🏰',
    requiredTags: { defense: 2 },
    effect: 'improved_regen',
    value: 8,
  },
  GOLD_RUSH: {
    id: 'gold_rush',
    name: 'Gold Rush',
    description: 'Permanenter 1.5x Score-Multiplikator',
    icon: '💎💎',
    requiredTags: { score: 3 },
    effect: 'permanent_score_mult',
    value: 1.5,
  },
  SCHOLAR: {
    id: 'scholar',
    name: 'Scholar',
    description: 'XP-Schwelle für Level-Up sinkt um 20%',
    icon: '📚',
    requiredTags: { xp: 2 },
    effect: 'reduced_xp_threshold',
    value: 0.8,
  },
  HOT_STREAK: {
    id: 'hot_streak',
    name: 'Hot Streak',
    description: 'Streak-Bonus skaliert exponentiell — lange Streaks werden massiv belohnt',
    icon: '🔥🔥',
    requiredTags: { streak: 2 },
    effect: 'exponential_streak_bonus',
    value: 2,
  },
  FORTUNE: {
    id: 'fortune',
    name: 'Fortune',
    description: 'Level-Up bietet 4 Optionen statt 3',
    icon: '🎰',
    requiredTags: { luck: 2 },
    effect: 'extra_pick_option',
    value: 4,
  },
  BERSERKER: {
    id: 'berserker',
    name: 'Berserker',
    description: '2x XP + 2x Score wenn nur noch 1 Leben',
    icon: '😤',
    requiredTags: { score: 1, defense: 1, streak: 1 },
    effect: 'low_hp_bonus',
    value: 2,
  },
  INFINITE_ENGINE: {
    id: 'infinite_engine',
    name: 'Infinite Engine',
    description: 'Snowball-Scaling verdreifacht sich',
    icon: '♾️',
    requiredTags: { score: 4 },
    effect: 'triple_snowball',
    value: 3,
  },
  JACKPOT: {
    id: 'jackpot',
    name: 'Jackpot',
    description: 'Jede 10. richtige Antwort: Score ×10',
    icon: '🎰🎰',
    requiredTags: { luck: 3 },
    effect: 'jackpot',
    value: 10,
  },
  UNSTOPPABLE: {
    id: 'unstoppable',
    name: 'Unstoppable',
    description: 'Streak wird bei Fehler gar nicht reduziert',
    icon: '🔥🛡️🔥',
    requiredTags: { streak: 2, defense: 2 },
    effect: 'streak_immune',
    value: 0,
  },

  // === CHEAT THE SYSTEM Synergien ===
  CHEATER: {
    id: 'cheater',
    name: 'Cheater',
    description: 'Gefakte Bedingungen geben doppelten Bonus statt normalen',
    icon: '🃏🃏',
    requiredTags: { fake: 2 },
    effect: 'double_fake_bonus',
    value: 2,
  },
  MASOCHIST: {
    id: 'masochist',
    name: 'Masochist',
    description: 'Jeder Lebensverlust gibt permanent +20% Multiplikator für den ganzen Run',
    icon: '🩸🩸',
    requiredTags: { sacrifice: 1, defense: 1 },
    effect: 'permanent_damage_mult',
    value: 0.2,
  },
  ASCENSION: {
    id: 'ascension',
    name: 'Ascension',
    description: 'Overflow-Heilung gibt ×1.5 Score-Multiplikator statt flat 100',
    icon: '🫀✨',
    requiredTags: { defense: 3 },
    effect: 'overflow_multiplier',
    value: 1.5,
  },
  PHANTOM_POWER: {
    id: 'phantom_power',
    name: 'Phantom Power',
    description: 'Fake-Relics zählen doppelt für Tag-Counts (aktiviert mehr Synergien)',
    icon: '👻⚡',
    requiredTags: { fake: 1, luck: 1 },
    effect: 'fake_double_tags',
    value: 2,
  },
  SACRIFICE_REWARD: {
    id: 'sacrifice_reward',
    name: 'Sacrifice Reward',
    description: 'Pro Sacrifice-Relic: +50% globaler Multiplikator',
    icon: '🔥💀',
    requiredTags: { sacrifice: 2 },
    effect: 'per_sacrifice_mult',
    value: 0.5,
  },
};
