export const SYNERGIES = {
  SPEED_DEMON: {
    id: 'speed_demon_combo',
    name: 'Speed Demon',
    description: 'Alle Timer-Boni werden verdoppelt',
    icon: '⚡⚡',
    requiredTags: { speed: 2 },
    effect: 'double_time_bonus',
    value: 2,
  },
  FORTRESS: {
    id: 'fortress',
    name: 'Fortress',
    description: 'Herz-Regen alle 8 statt 15 richtige Antworten',
    icon: '🏰',
    requiredTags: { defense: 2 },
    effect: 'improved_regen',
    value: 8,
  },
  GOLD_RUSH: {
    id: 'gold_rush',
    name: 'Gold Rush',
    description: 'Permanenter 1.5x Score-Multiplikator',
    icon: '💎💎',
    requiredTags: { score: 3 },
    effect: 'permanent_score_mult',
    value: 1.5,
  },
  SCHOLAR: {
    id: 'scholar',
    name: 'Scholar',
    description: 'XP-Schwelle für Level-Up sinkt um 20%',
    icon: '📚',
    requiredTags: { xp: 2 },
    effect: 'reduced_xp_threshold',
    value: 0.8,
  },
  HOT_STREAK: {
    id: 'hot_streak',
    name: 'Hot Streak',
    description: 'Streak-Bonus skaliert exponentiell — lange Streaks werden massiv belohnt',
    icon: '🔥🔥',
    requiredTags: { streak: 2 },
    effect: 'exponential_streak_bonus',
    value: 2,
  },
  FORTUNE: {
    id: 'fortune',
    name: 'Fortune',
    description: 'Level-Up bietet 4 Optionen statt 3',
    icon: '🎰',
    requiredTags: { luck: 2 },
    effect: 'extra_pick_option',
    value: 4,
  },
  BERSERKER: {
    id: 'berserker',
    name: 'Berserker',
    description: '2x XP + 2x Score wenn nur noch 1 Leben',
    icon: '😤',
    requiredTags: { score: 1, defense: 1, streak: 1 },
    effect: 'low_hp_bonus',
    value: 2,
  },
};
