export const SYNERGIES = {
  SPEED_DEMON: {
    id: 'speed_demon_combo',
    name: 'Speed Demon',
    description: 'All timer bonuses are doubled',
    icon: '⚡⚡',
    requiredTags: { speed: 2 },
    effect: 'double_time_bonus',
    value: 2,
  },
  FORTRESS: {
    id: 'fortress',
    name: 'Fortress',
    description: 'Regenerate a life every 8 correct answers instead of 15',
    icon: '🏰',
    requiredTags: { defense: 2 },
    effect: 'improved_regen',
    value: 8,
  },
  GOLD_RUSH: {
    id: 'gold_rush',
    name: 'Gold Rush',
    description: 'Permanent 1.5× score multiplier',
    icon: '💎💎',
    requiredTags: { score: 3 },
    effect: 'permanent_score_mult',
    value: 1.5,
  },
  SCHOLAR: {
    id: 'scholar',
    name: 'Scholar',
    description: 'XP threshold for leveling up is reduced by 20%',
    icon: '📚',
    requiredTags: { xp: 2 },
    effect: 'reduced_xp_threshold',
    value: 0.8,
  },
  HOT_STREAK: {
    id: 'hot_streak',
    name: 'Hot Streak',
    description: 'Streak bonus scales exponentially — long streaks are massively rewarded',
    icon: '🔥🔥',
    requiredTags: { streak: 2 },
    effect: 'exponential_streak_bonus',
    value: 2,
  },
  FORTUNE: {
    id: 'fortune',
    name: 'Fortune',
    description: 'Level-up offers 4 choices instead of 3',
    icon: '🎰',
    requiredTags: { luck: 2 },
    effect: 'extra_pick_option',
    value: 4,
  },
  BERSERKER: {
    id: 'berserker',
    name: 'Berserker',
    description: '2× XP + 2× score when down to 1 life',
    icon: '😤',
    requiredTags: { score: 1, defense: 1, streak: 1 },
    effect: 'low_hp_bonus',
    value: 2,
  },
  INFINITE_ENGINE: {
    id: 'infinite_engine',
    name: 'Infinite Engine',
    description: 'Snowball scaling triples',
    icon: '♾️',
    requiredTags: { score: 4 },
    effect: 'triple_snowball',
    value: 3,
  },
  JACKPOT: {
    id: 'jackpot',
    name: 'Jackpot',
    description: 'Every 10th correct answer: score ×10',
    icon: '🎰🎰',
    requiredTags: { luck: 3 },
    effect: 'jackpot',
    value: 10,
  },
  UNSTOPPABLE: {
    id: 'unstoppable',
    name: 'Unstoppable',
    description: 'Streak is not reduced at all on a wrong answer',
    icon: '🔥🛡️🔥',
    requiredTags: { streak: 2, defense: 2 },
    effect: 'streak_immune',
    value: 0,
  },

  // === CHEAT THE SYSTEM Synergien ===
  CHEATER: {
    id: 'cheater',
    name: 'Cheater',
    description: 'Faked conditions grant double their bonus instead of normal',
    icon: '🃏🃏',
    requiredTags: { fake: 2 },
    effect: 'double_fake_bonus',
    value: 2,
  },
  MASOCHIST: {
    id: 'masochist',
    name: 'Masochist',
    description: 'Each life lost permanently adds +20% multiplier for the entire run',
    icon: '🩸🩸',
    requiredTags: { sacrifice: 1, defense: 1 },
    effect: 'permanent_damage_mult',
    value: 0.2,
  },
  ASCENSION: {
    id: 'ascension',
    name: 'Ascension',
    description: 'Overflow healing grants ×1.5 score multiplier instead of a flat 100',
    icon: '🫀✨',
    requiredTags: { defense: 3 },
    effect: 'overflow_multiplier',
    value: 1.5,
  },
  PHANTOM_POWER: {
    id: 'phantom_power',
    name: 'Phantom Power',
    description: 'Fake relics count double toward tag counts (activates more synergies)',
    icon: '👻⚡',
    requiredTags: { fake: 1, luck: 1 },
    effect: 'fake_double_tags',
    value: 2,
  },
  SACRIFICE_REWARD: {
    id: 'sacrifice_reward',
    name: 'Sacrifice Reward',
    description: 'Per sacrifice relic: +50% global multiplier',
    icon: '🔥💀',
    requiredTags: { sacrifice: 2 },
    effect: 'per_sacrifice_mult',
    value: 0.5,
  },
};
